In [4]:
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.impute import SimpleImputer


In [5]:
iris = datasets.load_iris()
iris
x= iris.data
y= iris.target
x,y

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [6]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [7]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [8]:
wine = datasets.load_wine()
wine.data

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [9]:
wine.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [10]:
wine.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [11]:
wine.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [12]:
x[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [13]:
x[-5:]

array([[6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [14]:
x[:1]

array([[5.1, 3.5, 1.4, 0.2]])

In [15]:
x[-1:]

array([[5.9, 3. , 5.1, 1.8]])

In [16]:
x[:,0::3]

array([[5.1, 0.2],
       [4.9, 0.2],
       [4.7, 0.2],
       [4.6, 0.2],
       [5. , 0.2],
       [5.4, 0.4],
       [4.6, 0.3],
       [5. , 0.2],
       [4.4, 0.2],
       [4.9, 0.1],
       [5.4, 0.2],
       [4.8, 0.2],
       [4.8, 0.1],
       [4.3, 0.1],
       [5.8, 0.2],
       [5.7, 0.4],
       [5.4, 0.4],
       [5.1, 0.3],
       [5.7, 0.3],
       [5.1, 0.3],
       [5.4, 0.2],
       [5.1, 0.4],
       [4.6, 0.2],
       [5.1, 0.5],
       [4.8, 0.2],
       [5. , 0.2],
       [5. , 0.4],
       [5.2, 0.2],
       [5.2, 0.2],
       [4.7, 0.2],
       [4.8, 0.2],
       [5.4, 0.4],
       [5.2, 0.1],
       [5.5, 0.2],
       [4.9, 0.2],
       [5. , 0.2],
       [5.5, 0.2],
       [4.9, 0.1],
       [4.4, 0.2],
       [5.1, 0.2],
       [5. , 0.3],
       [4.5, 0.3],
       [4.4, 0.2],
       [5. , 0.6],
       [5.1, 0.4],
       [4.8, 0.3],
       [5.1, 0.2],
       [4.6, 0.2],
       [5.3, 0.2],
       [5. , 0.2],
       [7. , 1.4],
       [6.4, 1.5],
       [6.9,

split dataset

In [17]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.7)
x_train.shape

(105, 4)

In [18]:
x_test.shape

(45, 4)

In [19]:
y_train.shape

(105,)

In [20]:
y_test.shape

(45,)

In [21]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.5)
x_train.shape

(75, 4)

In [22]:
x_test.shape

(75, 4)

In [23]:
y_train.shape

(75,)

In [24]:
y_test.shape


(75,)

In [25]:
x_train.size

300

In [26]:
data = [[1,2],[np.nan,3],[4,2]]
imputer = SimpleImputer(missing_values=np.nan,strategy='constant',fill_value=-999)
#imputer.fit(data)
imputer.fit_transform(data)

array([[   1.,    2.],
       [-999.,    3.],
       [   4.,    2.]])

In [27]:
data = [[1,2],[np.nan,3],[4,2]]
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit_transform(data)

array([[1. , 2. ],
       [2.5, 3. ],
       [4. , 2. ]])

In [28]:
data = [[1,2],[np.nan,3],[4,2],[5,7],[8,9]]
imputer = SimpleImputer(missing_values=np.nan,strategy='median')
imputer.fit_transform(data)

array([[1. , 2. ],
       [4.5, 3. ],
       [4. , 2. ],
       [5. , 7. ],
       [8. , 9. ]])

In [29]:
data = [[1,2],[np.nan,3],[4,2],[5,3],[3,9]]
imputer_mode = SimpleImputer(missing_values=np.nan,strategy='most_frequent')
imputer_mode.fit_transform(data)

array([[1., 2.],
       [1., 3.],
       [4., 2.],
       [5., 3.],
       [3., 9.]])

In [30]:
student = pd.read_csv('students.csv')
student

name   age  gender      genre
0     A  20.0       0     HipHop
1     B  23.0       0     HipHop
2     C  25.0       0        NaN
3     D  26.0       0       Jazz
4     E  29.0       0       Jazz
5     F  30.0       0       Jazz
6     G   NaN       0  Classical
7     H  33.0       0  Classical
8     I  37.0       0  Classical
9     J  20.0       1      Dance
10    K  21.0       1        NaN
11    L  25.0       1      Dance
12    M  26.0       1   Acoustic
13    N   NaN       1   Acoustic
14    O  30.0       1   Acoustic
15    P  31.0       1  Classical
16    Q  34.0       1  Classical
17    R   NaN       1  Classical
18    A  20.0       0     HipHop
19    H  33.0       0  Classical

In [31]:
df_age = np.array(student['age']).reshape(-1,1)
df_age

array([[20.],
       [23.],
       [25.],
       [26.],
       [29.],
       [30.],
       [nan],
       [33.],
       [37.],
       [20.],
       [21.],
       [25.],
       [26.],
       [nan],
       [30.],
       [31.],
       [34.],
       [nan],
       [20.],
       [33.]])

In [32]:
imputer_mean = SimpleImputer(missing_values=np.nan,strategy='mean')
imputer_mean.fit_transform(df_age)

array([[20.        ],
       [23.        ],
       [25.        ],
       [26.        ],
       [29.        ],
       [30.        ],
       [27.23529412],
       [33.        ],
       [37.        ],
       [20.        ],
       [21.        ],
       [25.        ],
       [26.        ],
       [27.23529412],
       [30.        ],
       [31.        ],
       [34.        ],
       [27.23529412],
       [20.        ],
       [33.        ]])

In [33]:
student['age'] = imputer_mean.fit_transform(df_age)
student

name        age  gender      genre
0     A  20.000000       0     HipHop
1     B  23.000000       0     HipHop
2     C  25.000000       0        NaN
3     D  26.000000       0       Jazz
4     E  29.000000       0       Jazz
5     F  30.000000       0       Jazz
6     G  27.235294       0  Classical
7     H  33.000000       0  Classical
8     I  37.000000       0  Classical
9     J  20.000000       1      Dance
10    K  21.000000       1        NaN
11    L  25.000000       1      Dance
12    M  26.000000       1   Acoustic
13    N  27.235294       1   Acoustic
14    O  30.000000       1   Acoustic
15    P  31.000000       1  Classical
16    Q  34.000000       1  Classical
17    R  27.235294       1  Classical
18    A  20.000000       0     HipHop
19    H  33.000000       0  Classical

In [34]:
student['genre']

0        HipHop
1        HipHop
2           NaN
3          Jazz
4          Jazz
5          Jazz
6     Classical
7     Classical
8     Classical
9         Dance
10          NaN
11        Dance
12     Acoustic
13     Acoustic
14     Acoustic
15    Classical
16    Classical
17    Classical
18       HipHop
19    Classical
Name: genre, dtype: object

In [35]:
df_genre = np.array(student['genre']).reshape(-1,1)
df_genre

array([['HipHop'],
       ['HipHop'],
       [nan],
       ['Jazz'],
       ['Jazz'],
       ['Jazz'],
       ['Classical'],
       ['Classical'],
       ['Classical'],
       ['Dance'],
       [nan],
       ['Dance'],
       ['Acoustic'],
       ['Acoustic'],
       ['Acoustic'],
       ['Classical'],
       ['Classical'],
       ['Classical'],
       ['HipHop'],
       ['Classical']], dtype=object)

In [36]:
imputer_genre = SimpleImputer(missing_values=np.nan,strategy='most_frequent')
imputer_genre.fit_transform(df_genre)

array([['HipHop'],
       ['HipHop'],
       ['Classical'],
       ['Jazz'],
       ['Jazz'],
       ['Jazz'],
       ['Classical'],
       ['Classical'],
       ['Classical'],
       ['Dance'],
       ['Classical'],
       ['Dance'],
       ['Acoustic'],
       ['Acoustic'],
       ['Acoustic'],
       ['Classical'],
       ['Classical'],
       ['Classical'],
       ['HipHop'],
       ['Classical']], dtype=object)

In [37]:
student['genre'] = imputer_genre.fit_transform(df_genre)
student

name        age  gender      genre
0     A  20.000000       0     HipHop
1     B  23.000000       0     HipHop
2     C  25.000000       0  Classical
3     D  26.000000       0       Jazz
4     E  29.000000       0       Jazz
5     F  30.000000       0       Jazz
6     G  27.235294       0  Classical
7     H  33.000000       0  Classical
8     I  37.000000       0  Classical
9     J  20.000000       1      Dance
10    K  21.000000       1  Classical
11    L  25.000000       1      Dance
12    M  26.000000       1   Acoustic
13    N  27.235294       1   Acoustic
14    O  30.000000       1   Acoustic
15    P  31.000000       1  Classical
16    Q  34.000000       1  Classical
17    R  27.235294       1  Classical
18    A  20.000000       0     HipHop
19    H  33.000000       0  Classical

In [38]:
data = np.array([1,2,4.4,5,6,-30,6,-40,20]).reshape(-1,1)
data_bin = preprocessing.Binarizer(threshold=4).transform(data)
data_bin

array([[0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.]])

In [39]:
color = ['blue','white','black']
le = preprocessing.LabelEncoder()
le.fit_transform(color)

array([1, 2, 0], dtype=int64)

In [45]:
student['genre']


0        HipHop
1        HipHop
2     Classical
3          Jazz
4          Jazz
5          Jazz
6     Classical
7     Classical
8     Classical
9         Dance
10    Classical
11        Dance
12     Acoustic
13     Acoustic
14     Acoustic
15    Classical
16    Classical
17    Classical
18       HipHop
19    Classical
Name: genre, dtype: object

In [47]:
s_gen = preprocessing.LabelEncoder()
s_gen.fit_transform(genre)


0     3
1     3
2     1
3     4
4     4
5     4
6     1
7     1
8     1
9     2
10    1
11    2
12    0
13    0
14    0
15    1
16    1
17    1
18    3
19    1
Name: genre, dtype: int32

In [48]:
data = [2,3],[4,6],[8,4]
scalar_minmax = preprocessing.MinMaxScaler(feature_range=(0,1))
scalar_minmax.fit_transform(data)

array([[0.        , 0.        ],
       [0.33333333, 1.        ],
       [1.        , 0.33333333]])

In [49]:
data = [2,3],[3,4],[5,8]
scalar_std = preprocessing.StandardScaler()
scalar_std.fit_transform(data)


array([[-1.06904497, -0.9258201 ],
       [-0.26726124, -0.46291005],
       [ 1.33630621,  1.38873015]])

In [50]:
titanic = pd.read_csv("seaborn-data/titanic.csv")
titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]